Blog/urls.py
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Blogs.urls')),
    path('users/',include('users.urls')),
    
]

Blogs/urls.py
"""Defining urls patterns for Blogs app."""
from django.urls import path
from . import views

app_name = 'Blogs'

urlpatterns = [
    #homepage
    path('',views.home, name = 'home'),
    # New post page
    path('new_post',views.new_post, name = 'new_post'),
    # Edit post
    path('edit_post/<int:post_id>/',views.edit_post, name= 'edit_post'),
]

users/urls.py
""" Defining urls patterns for the users app."""
from django.urls import path, include
from . import views
app_name = 'users'

urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/',views.register, name= 'register'),
]

Blogs/models.py
from typing import Text
from django.db import models
from django.urls.converters import StringConverter
from django.contrib.auth.models import User

class BlogPost(models.Model):
    Title = models.CharField(max_length = 40) 
    Text = models.CharField(max_length = 1000)
    date_added = models.DateTimeField(auto_now = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return  self.Title

users/models.py
from django.db import models

# Create your models here.

Blogs/forms.py
from django import forms
from django.db.models import fields
from .models import BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['Title','Text']
        labels = {'Text':'Text','Title':'Tittle'}
        widgets = {'Text': forms.Textarea(attrs={'cols':80}),'Title': forms.Textarea(attrs={'cols':40,'rows':2})}

        

Blogs/views.py
from django.http.response import Http404
from django.shortcuts import render, redirect
from .models import BlogPost
from .forms import BlogForm 
from django.contrib.auth.decorators import login_required


def home(request):
    """Render the Home page, Showing all the posts"""
    posts = BlogPost.objects.order_by('date_added')
    context = {'posts':posts}
    return render(request, 'Blogs/home.html', context)

@login_required
def new_post(request):
    """Adds a new post."""
    if request.method != "POST":
        # No data submitted; create a new form
        form = BlogForm()
    else:
        # Post data submitted; porcess data.
        form = BlogForm(data = request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('Blogs:home')
    # Display a blank or invalid form.
    context = {'form':form}
    return render(request,'Blogs/new_post.html',context)

@login_required
def edit_post(request, post_id):
    """ Edit existing posts."""
    post = BlogPost.objects.get(id = post_id)
    check_if_user_owns_data(request, post)
    if request.method != 'POST':
        # Initial request; pre-fill form with the current post.
        form = BlogForm(instance = post)
    else:
        # POST data submitted; process data.
        form = BlogForm(instance = post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('Blogs:home')
    
    context = {'post':post,'form':form}
    return render(request, 'Blogs/edit_post.html', context)

def check_if_user_owns_data(request, post):
    """ Evaluates if the owner of the post matches the current user."""
    if post.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """ Register a new user."""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('Blogs:home')
    # Display a blank or invalid form
    context = {'form':form}
    return render(request, 'registration/register.html', context)

Blogs/templates/Blogs/Base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Blog</title>


  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}


</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'Blogs:home' %}">Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text"}">Hello, {{user.username}}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
        {% endif %}


      </ul>

    </div>

  </nav>
  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

Blogs/templates/Blogs/edit_post.html
{% extends "Blogs/Base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Edit post</h2>
{% endblock page_header %}

{%block content%}
  <form action = "{%url 'Blogs:edit_post' post.id%}" method="post" class="form">
    {%csrf_token%}
    {% bootstrap_form form %}
    <button name="submit" class="btn btn-primary">Save changes</button>
  </form>


{%endblock content%}

Blogs/templates/Blogs/home.html
{% extends 'Blogs/Base.html' %}
{% block page_header %}
  <h1>Posts:</h1>
{% endblock page_header %}
{%block content%}
  <ul>
    {% for post in posts %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{post.Title}}    
        <small>{{post.date_added}} <a href="{%url 'Blogs:edit_post' post.id %} " class="btn btn-secondary"> Edit Post</a></small>
      </h4>
    <div class="card-body">
      {{post.Text|linebreaks}}
    </div>
    </div>
    {%empty%}
    <li>Be the first one on posting!!!</li>
    {%endfor%}

  </ul>
  <h6><a href="{% url 'Blogs:new_post' %}"> Add Post </a></h6>

{%endblock content%}

Blogs/templates/Blogs/new_post.html
{%extends 'Blogs/Base.html' %}

{%block content%}
  <p>Writte here your Post:</p>
  <form action = "{% url 'Blogs:new_post' %}" method = 'post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name = "submit"> Add new post </button>
  </form>




{%endblock content%}